# Generated by Django 2.0.2 on 2019-05-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lookin_age_to',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_age_from',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_sex',
        ),
    ]
