# Generated by Django 2.0.2 on 2019-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_looking_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lookin_age_to',
            field=models.IntegerField(default=99, verbose_name='Возраст поиска верхний'),
        ),
    ]
