# Generated by Django 2.0.2 on 2019-05-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_user_looking_age_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
    ]
