# Generated by Django 2.0.2 on 2019-05-14 09:24

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20190514_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banned_ids',
            field=models.CharField(blank=True, default=None, max_length=999999999, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Забаненные айди'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_ids',
            field=models.CharField(blank=True, default=None, max_length=999999999, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Пролайканные айди'),
        ),
        migrations.AlterField(
            model_name='user',
            name='paired_ids',
            field=models.CharField(blank=True, default=None, max_length=999999999, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Парные айди'),
        ),
    ]
